export const DEFAULT_QUICK_TEMPLATES = [
  {
    id: 'reservation-proposal',
    label: 'Proposition réservation',
    icon: 'CalendarPlus',
    enabled: true,
    titlePrefix: 'Relancer proposition de réservation',
    referenceLabel: 'Client ou référence',
    referenceQuestion: 'Pour quel client ou quelle référence ?',
    referencePlaceholder: 'Nom du client, numéro de dossier...',
    firstDateLabel: 'Date d’envoi',
    firstDateQuestion: 'À quelle date la proposition a-t-elle été envoyée ?',
    dueDateLabel: 'Date de relance',
    dueDateQuestion: 'Quand faut-il relancer si aucune réponse n’arrive ?',
    category: 'Réservation',
    priority: 'Normale',
    status: 'En attente'
  },
  {
    id: 'maintenance',
    label: 'Maintenance',
    icon: 'Wrench',
    enabled: true,
    titlePrefix: 'Maintenance à traiter',
    referenceLabel: 'Chambre ou lieu',
    referenceQuestion: 'Quelle chambre ou quel lieu est concerné ?',
    referencePlaceholder: 'Chambre 204, lobby, ascenseur...',
    detailLabel: 'Problème',
    detailQuestion: 'Quel problème a été constaté ?',
    detailPlaceholder: 'Ampoule, fuite, climatisation, serrure...',
    dueDateLabel: 'Date souhaitée',
    dueDateQuestion: 'Pour quelle date l’intervention est-elle souhaitée ?',
    category: 'Maintenance',
    priority: 'Normale',
    status: 'À faire'
  },
  {
    id: 'housekeeping',
    label: 'Ménage',
    icon: 'BedDouble',
    enabled: true,
    titlePrefix: 'Ménage à suivre',
    referenceLabel: 'Chambre ou zone',
    referenceQuestion: 'Quelle chambre ou zone est concernée ?',
    referencePlaceholder: 'Chambre 118, salle petit-déjeuner...',
    detailLabel: 'Action demandée',
    detailQuestion: 'Quelle action faut-il demander au ménage ?',
    detailPlaceholder: 'Préparer lit bébé, serviettes, recouche...',
    dueDateLabel: 'À faire avant',
    dueDateQuestion: 'Pour quand faut-il le faire ?',
    category: 'Ménage',
    priority: 'Normale',
    status: 'À faire'
  },
  {
    id: 'billing',
    label: 'Facturation',
    icon: 'ReceiptText',
    enabled: true,
    titlePrefix: 'Facturation à vérifier',
    referenceLabel: 'Client ou dossier',
    referenceQuestion: 'Quel client ou dossier est concerné ?',
    referencePlaceholder: 'Nom client, société, numéro facture...',
    detailLabel: 'Point à vérifier',
    detailQuestion: 'Quel point de facturation faut-il vérifier ?',
    detailPlaceholder: 'Avoir, taxe de séjour, paiement, facture société...',
    dueDateLabel: 'Date limite',
    dueDateQuestion: 'Quelle est la date limite de traitement ?',
    category: 'Facturation',
    priority: 'Normale',
    status: 'À faire'
  },
  {
    id: 'luggage',
    label: 'Bagagerie',
    icon: 'Luggage',
    enabled: true,
    titlePrefix: 'Bagagerie à suivre',
    referenceLabel: 'Client ou étiquette',
    referenceQuestion: 'Quel client ou numéro d’étiquette ?',
    referencePlaceholder: 'Nom client, numéro étiquette...',
    firstDateLabel: 'Date de dépôt',
    firstDateQuestion: 'À quelle date les bagages ont-ils été déposés ?',
    detailLabel: 'Information utile',
    detailQuestion: 'Y a-t-il une information utile à noter ?',
    detailPlaceholder: 'Nombre de bagages, consigne spéciale...',
    detailRequired: false,
    dueDateLabel: 'Date de suivi',
    dueDateQuestion: 'Quand faut-il suivre ou récupérer les bagages ?',
    category: 'Bagagerie',
    priority: 'Normale',
    status: 'En attente'
  },
  {
    id: 'client-request',
    label: 'Demande client',
    icon: 'UserRound',
    enabled: true,
    titlePrefix: 'Demande client',
    referenceLabel: 'Client ou chambre',
    referenceQuestion: 'Quel client ou quelle chambre ?',
    referencePlaceholder: 'Nom client, chambre 305...',
    detailLabel: 'Demande',
    detailQuestion: 'Quelle est la demande du client ?',
    detailPlaceholder: 'Taxi, oreiller, late check-out, information...',
    dueDateLabel: 'À traiter le',
    dueDateQuestion: 'Quand faut-il traiter cette demande ?',
    category: 'Client',
    priority: 'Normale',
    status: 'À faire'
  },
  {
    id: 'direction',
    label: 'Direction',
    icon: 'BriefcaseBusiness',
    enabled: true,
    titlePrefix: 'Consigne direction',
    referenceLabel: 'Sujet',
    referenceQuestion: 'Quel est le sujet ?',
    referencePlaceholder: 'Contrat, incident, retour client...',
    detailLabel: 'Consigne',
    detailQuestion: 'Quelle est la consigne de direction ?',
    detailPlaceholder: 'Information ou action demandée par la direction...',
    dueDateLabel: 'Date limite',
    dueDateQuestion: 'Quelle est la date limite ?',
    category: 'Direction',
    priority: 'Normale',
    status: 'À faire'
  }
];

export const DEFAULT_ADMIN_SETTINGS = {
  defaultsVersion: 2,
  kanbanWindowDays: 5,
  kanbanExcludedCategories: ['Maintenance', 'Facturation', 'Direction', 'Autre'],
  quickTemplates: DEFAULT_QUICK_TEMPLATES,
  shiftChecklists: []
};
